namespace Anchor.Domain.Enums
{
    public enum BibleBook
    {
        // Antigo Testamento
        Genesis = 1,
        Exodus,
        Leviticus,
        Numbers,
        Deuteronomy,

        Joshua,
        Judges,
        Ruth,
        FirstSamuel,
        SecondSamuel,
        FirstKings,
        SecondKings,
        FirstChronicles,
        SecondChronicles,
        Ezra,
        Nehemiah,
        Esther,

        Job,
        Psalms,
        Proverbs,
        Ecclesiastes,
        SongOfSolomon,

        Isaiah,
        Jeremiah,
        Lamentations,
        Ezekiel,
        Daniel,

        Hosea,
        Joel,
        Amos,
        Obadiah,
        Jonah,
        Micah,
        Nahum,
        Habakkuk,
        Zephaniah,
        Haggai,
        Zechariah,
        Malachi,

        // Novo Testamento
        Matthew,
        Mark,
        Luke,
        John,
        Acts,
        Romans,
        FirstCorinthians,
        SecondCorinthians,
        Galatians,
        Ephesians,
        Philippians,
        Colossians,
        FirstThessalonians,
        SecondThessalonians,
        FirstTimothy,
        SecondTimothy,
        Titus,
        Philemon,
        Hebrews,
        James,
        FirstPeter,
        SecondPeter,
        FirstJohn,
        SecondJohn,
        ThirdJohn,
        Jude,
        Revelation
    }
}
